# version: '3.8'
services:
    micro-base:
        build: ./apps/micro-base
        ports:
            - '3000:3000'
    react-app:
        build: ./apps/react-app
        ports:
            - '3001:3000'
    nginx:
        image: nginx:alpine
        ports:
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - micro-base
            - react-app
